### ISSUE TITLE
Digraphs

### ISSUE THREAD

**Issue by francisco285** [LukeSmithxyz/vimling#6]
You don't need to define/undefine keymaps, apparently vim already has this feature (`:h digraphs`):

```
Digraphs are used to enter characters that normally cannot be entered by
an ordinary keyboard.  These are mostly printable non-ASCII characters.  The
digraphs are easier to remember than the decimal number that can be entered
with CTRL-V (see |i_CTRL-V|).
```

Ex.: In insert mode, pressing `<C-k>c,` gives you `ç`
You can see all digraphs with `:digraphs<CR>` and you can define your owns with `:digraph <char1> <char2> <number>`, where `<number>` is the decimal representation of the character.

(I don't know if it also works in vim, as I'm actually using Neovim)
I don't use this plugin, but I thought you would like to know about this feature.

**Comment by Xavier-Waters** [comment]
https://invidious-us.kavin.rocks/watch?v=WPvvOEiiF28

Luke explains why he doesn't use digraphs here (and yes digraphs are available in normal vim).
